### ISSUE TITLE
Block comments in function definitions resets indentation

### ISSUE THREAD

**Issue by anissen** [snowkit/atom-haxe#54]
If I have a function definition, e.g. 
`function test(a :Int, b :String) {`
and add a block comment like this:
`function test(a :Int, b :String /* hack */) {`
then all indentation is lost.

**Comment by jeremyfa** [comment]
Interesting,

I might be wrong, but such issue could also come from the `language-haxe` plugin.

Do you still have the indentation issue if you disable the `atom-haxe` plugin but keep the `language-haxe` plugin enabled? (That will help knowing where does the issue comes from).

**Comment by anissen** [comment]
> Do you still have the indentation issue if you disable the atom-haxe plugin but keep the language-haxe plugin enabled? (That will help knowing where does the issue comes from).

Yes, the problem goes away if I disable `atom-haxe` (with `language-haxe` enabled) and reappears if I disable `language-haxe` and enable `atom-haxe`.

Additionally, the problem seems to occur when an inline block comment is _closed_ inside _parentheses_ or _curly brackets_, i.e. `(/**/)` and `{/**}`).

**Comment by jeremyfa** [comment]
Then the problem may come from this file: https://github.com/snowkit/atom-haxe/blob/master/settings/haxe.cson

@underscorediscovery were there specific reasons to add this file in `atom-haxe`, in addition to what is available already in the `language-haxe` plugin?

**Comment by ruby0x1** [comment]
at the time the `language-haxe` plugin wasn't updated for > a year, plus the author did not reply to any of my contact attempts (and still hasn't). I included it to solve some issues, because it was unusable otherwise in combination. 

From what I recall, I think my inclusion was specific to the comments and not indentation rules but it was a long time back. You could probably remove the indentation rules but the `cmd+/` shortcut should be tested against removing the file entirely, as I don't think the language haxe correctly configured that at the time and may have resolved that issue since.
